"""Hook script integrity verification (sha256 manifest check).

CLAUDE.md (line 34) commits to "hash-verified hook scripts". This module
implements that contract: each hook execution can verify its own bytes
against a committed manifest, refusing to run (or warning) on mismatch.

Modes (env: ``AIENG_HOOK_INTEGRITY_MODE``):

* ``enforce`` (default, spec-120 follow-up) -- fail-closed. Mismatch raises
  SystemExit(2) so the IDE knows the hook refused. Use in CI / production /
  any branch with the manifest on disk and current.
* ``warn`` -- log a ``framework_error`` event but allow the hook to run.
  Use in dev workflows where hooks change frequently and you don't want to
  regenerate the manifest after every edit. Set
  ``AIENG_HOOK_INTEGRITY_MODE=warn`` in your shell rc.
* ``off`` -- skip the check entirely (no audit event).

The default flipped from ``warn`` to ``enforce`` after the spec-120
governance review confirmed the manifest is regenerated cleanly and the
``--check`` mode is stable. Fail-closed by default closes the gap where a
hook on disk silently drifted from the committed bytes.

The manifest path is ``.ai-engineering/state/hooks-manifest.json`` with
shape ``{"hooks": {"<repo-relative-path>": "<sha256-hex>"}, ...}``.
Regenerated by ``scripts/regenerate-hooks-manifest.py`` after any
intentional edit to a hook script.

Sealed contract: stdlib-only (no ``ai_engineering.*`` imports), matches
the rest of ``_lib``.
"""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

_MANIFEST_REL = Path(".ai-engineering") / "state" / "hooks-manifest.json"
# spec-147 G1: fail-closed by default. A hook whose bytes drift from the
# committed manifest (or is missing from it) MUST refuse to run when no env
# var relaxes the check. The dev escape hatch is the ``warn`` mode below.
_DEFAULT_MODE = "enforce"
_VALID_MODES: frozenset[str] = frozenset({"enforce", "warn", "off"})

# spec-147 G1: one-line, actionable hint appended to every enforce-mode
# failure reason so the fail-closed stderr line names BOTH the dev escape
# hatch and the recovery command. ``run_hook_safe`` writes the reason
# verbatim to stderr before exiting non-zero.
_ENFORCE_HINT = (
    "set AIENG_HOOK_INTEGRITY_MODE=warn to bypass during dev, or re-pin with "
    "python3 .ai-engineering/scripts/regenerate-hooks-manifest.py after an intentional edit"
)

# Module-level cache: load_manifest is called on every hook invocation. Cache
# keyed on (resolved path, mtime_ns) so edits during dev still bust the cache
# but warm invocations within a single process pay zero disk I/O.
_MANIFEST_CACHE: dict[tuple[str, int], dict[str, str]] = {}
_MANIFEST_CACHE_MAX = 4


def _resolve_mode() -> str:
    raw = (os.environ.get("AIENG_HOOK_INTEGRITY_MODE") or "").strip().lower()
    if raw in _VALID_MODES:
        return raw
    return _DEFAULT_MODE


def compute_file_sha256(path: Path) -> str:
    """Return canonical lowercase sha256 hex of ``path`` contents.

    Normalises CRLF -> LF before hashing so the result is identical on
    Windows / Linux / macOS regardless of how the runner checked out the
    repository. LF-only files hash to exactly the same digest as the
    legacy raw-bytes implementation.
    """
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def _load_manifest_section(project_root: Path, section_key: str) -> dict[str, str]:
    """Return ``{relative_path: sha256}`` from one manifest section.

    Memoized on (resolved manifest path, mtime_ns, section). Edits to the
    manifest bust the cache via mtime change.
    """
    manifest_path = project_root / _MANIFEST_REL
    try:
        stat = manifest_path.stat()
    except OSError:
        return {}
    cache_key = (str(manifest_path.resolve()), stat.st_mtime_ns, section_key)
    cached = _MANIFEST_CACHE.get(cache_key)
    if cached is not None:
        return cached
    try:
        payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError, ValueError):
        return {}
    section = payload.get(section_key) if isinstance(payload, dict) else None
    if not isinstance(section, dict):
        result: dict[str, str] = {}
    else:
        result = {str(k): str(v) for k, v in section.items() if isinstance(v, str)}
    if len(_MANIFEST_CACHE) >= _MANIFEST_CACHE_MAX:
        _MANIFEST_CACHE.pop(next(iter(_MANIFEST_CACHE)))
    _MANIFEST_CACHE[cache_key] = result
    return result


def load_manifest(project_root: Path) -> dict[str, str]:
    """Return ``{relative_path: sha256}`` for the ``hooks`` section.

    Memoized on (resolved manifest path, mtime_ns) so warm hook invocations
    within a single process skip the JSON parse. Edits to the manifest still
    bust the cache via mtime change.
    """
    return _load_manifest_section(project_root, "hooks")


def load_trusted_scripts(project_root: Path) -> dict[str, str]:
    """Return ``{relative_path: sha256}`` for the ``trustedScripts`` section.

    spec-131 sub-004 T-4.D: trusted-script lane stores hash-pinned entries
    in a separate manifest key so the prompt-injection-guard bypass can
    verify the script bytes independently of the hook integrity check.
    """
    return _load_manifest_section(project_root, "trustedScripts")


def verify_hook_integrity(script_path: Path, project_root: Path) -> tuple[bool, str | None]:
    """Verify ``script_path`` matches the committed manifest entry.

    Returns ``(ok, reason)``. ``ok=True`` means the script either matches
    or has no manifest entry (in non-enforce modes — forward-compat for new
    hooks not yet enrolled). ``reason`` is a short human-readable string when
    ok is False, suitable for telemetry summaries.

    In ``enforce`` mode an unenrolled hook is treated as a violation: dropping
    a new file into ``.ai-engineering/scripts/hooks/`` and wiring it from
    ``.claude/settings.json`` no longer skips the integrity check. ``warn``
    and ``off`` keep the lenient behaviour so day-one installs after the
    manifest landed don't brick.
    """
    manifest = load_manifest(project_root)
    if not manifest:
        return True, None
    try:
        rel = script_path.resolve().relative_to(project_root.resolve())
    except ValueError:
        # Hook lives outside the project; nothing to verify against.
        return True, None
    expected = manifest.get(rel.as_posix())
    if expected is None:
        if _resolve_mode() == "enforce":
            return False, f"hook {rel} not enrolled in hooks-manifest.json — {_ENFORCE_HINT}"
        return True, None
    actual = compute_file_sha256(script_path)
    if actual.lower() == expected.lower():
        return True, None
    reason = f"sha256 mismatch (expected {expected[:12]}…, got {actual[:12]}…)"
    if _resolve_mode() == "enforce":
        reason = f"{reason} — {_ENFORCE_HINT}"
    return False, reason


def verify_trusted_script(script_path: Path, project_root: Path) -> tuple[bool, str | None]:
    """Verify ``script_path`` matches its ``trustedScripts`` manifest entry.

    spec-131 sub-004 T-4.D / T-4.F: parallels :func:`verify_hook_integrity`
    but reads the ``trustedScripts`` section. Returns ``(True, None)`` when
    the script bytes match the pinned sha256. Returns ``(False, reason)``
    when the bytes drift OR the script is not enrolled in
    ``trustedScripts`` — drift on a trusted-lane script must always fail
    because the lane intentionally bypasses RTK rewriting and IOC
    re-evaluation. An unenrolled script signals a misconfiguration: the
    caller is asking for a bypass that the manifest does not pin.
    """
    manifest = load_trusted_scripts(project_root)
    if not manifest:
        return False, "trustedScripts section absent or empty"
    try:
        rel = script_path.resolve().relative_to(project_root.resolve())
    except ValueError:
        return False, "script lives outside project root"
    expected = manifest.get(rel.as_posix())
    if expected is None:
        return False, f"trusted script {rel} not enrolled in hooks-manifest.json"
    actual = compute_file_sha256(script_path)
    if actual.lower() == expected.lower():
        return True, None
    return False, f"trusted-script sha256 mismatch (expected {expected[:12]}…, got {actual[:12]}…)"


def integrity_mode() -> str:
    return _resolve_mode()


def manifest_path(project_root: Path) -> Path:
    return project_root / _MANIFEST_REL


__all__ = [
    "compute_file_sha256",
    "integrity_mode",
    "load_manifest",
    "load_trusted_scripts",
    "manifest_path",
    "verify_hook_integrity",
    "verify_trusted_script",
]
